menu:
  Blog: /
  About: /about/
  Works: /works/
  Archives: /archives/

# side_menu:
#   Blog: /
#   About: /about/
#   Projects: /projects/
#   Archives: /archives/


widgets:
- search
- menu
- subscribe
- recent_posts
- category
- tag

excerpt_link: Read More...

share:
  facebook: true
  twitter: true
  google: true
  linkedin: true

social:
  twitter: https://twitter.com/SuwandiRonald
  linkedin: http://au.linkedin.com/in/ronaldsuwandi/
  github: https://github.com/ronaldsuwandi
  email: mailto:ronald@ronaldsuwandi.com?subject=I LOVE YOU
  feed: /atom.xml

google_analytics: UA-28913151-4
# Fill this one to allow tracking for multiple subdomains
google_analytics_domain:

logo:
  url: /img/avatar/onepiece.jpg
  text: Ronald Suwandi

# if custom.js is required
custom_js: true